export const ADD_API_BRANDS_REQUEST = 'ADD_API_BRANDS_REQUEST';
export const ADD_API_BRANDS_SUCCEEDED = 'ADD_API_BRANDS_SUCCEEDED';
export const ADD_API_BRANDS_FAILED = 'ADD_API_BRANDS_FAILED';

export const GET_API_BRANDS_REQUEST = 'GET_API_BRANDS_REQUEST';
export const GET_API_BRANDS_SUCCEEDED = 'GET_API_BRANDS_SUCCEEDED';
export const GET_API_BRANDS_FAILED = 'GET_API_BRANDS_FAILED';

export const DELETE_API_BRANDS_REQUEST = 'DELETE_API_BRANDS_REQUEST';
export const DELETE_API_BRANDS_SUCCEEDED = 'DELETE_API_BRANDS_SUCCEEDED';
export const DELETE_API_BRANDS_FAILED = 'DELETE_API_BRANDS_FAILED';

export const EDIT_API_BRANDS_REQUEST = 'EDIT_API_BRANDS_REQUEST';
export const EDIT_API_BRANDS_SUCCEEDED = 'EDIT_API_BRANDS_SUCCEEDED';
export const EDIT_API_BRANDS_FAILED = 'EDIT_API_BRANDS_FAILED';
