export const ADD_API_REQUEST = 'ADD_API_REQUEST';
export const ADD_API_SUCCEEDED = 'ADD_API_SUCCEEDED';
export const ADD_API_FAILED = 'ADD_API_FAILED';

export const GET_API_REQUEST = 'GET_API_REQUEST';
export const GET_API_SUCCEEDED = 'GET_API_SUCCEEDED';
export const GET_API_FAILED = 'GET_API_FAILED';

export const DELETE_API_REQUEST = 'DELETE_API_REQUEST';
export const DELETE_API_SUCCEEDED = 'DELETE_API_SUCCEEDED';
export const DELETE_API_FAILED = 'DELETE_API_FAILED';

export const EDIT_API_REQUEST = 'EDIT_API_REQUEST';
export const EDIT_API_SUCCEEDED = 'EDIT_API_SUCCEEDED';
export const EDIT_API_FAILED = 'EDIT_API_FAILED';
