export const ADD_API_PRODUCTS_REQUEST = 'ADD_API_PRODUCTS_REQUEST';
export const ADD_API_PRODUCTS_SUCCEEDED = 'ADD_API_PRODUCTS_SUCCEEDED';
export const ADD_API_PRODUCTS_FAILED = 'ADD_API_PRODUCTS_FAILED';

export const GET_API_PRODUCTS_REQUEST = 'GET_API_PRODUCTS_REQUEST';
export const GET_API_PRODUCTS_SUCCEEDED = 'GET_API_PRODUCTS_SUCCEEDED';
export const GET_API_PRODUCTS_FAILED = 'GET_API_PRODUCTS_FAILED';

export const DELETE_API_PRODUCTS_REQUEST = 'DELETE_API_PRODUCTS_REQUEST';
export const DELETE_API_PRODUCTS_SUCCEEDED = 'DELETE_API_PRODUCTS_SUCCEEDED';
export const DELETE_API_PRODUCTS_FAILED = 'DELETE_API_PRODUCTS_FAILED';

export const EDIT_API_PRODUCTS_REQUEST = 'EDIT_API_PRODUCTS_REQUEST';
export const EDIT_API_PRODUCTS_SUCCEEDED = 'EDIT_API_PRODUCTS_SUCCEEDED';
export const EDIT_API_PRODUCTS_FAILED = 'EDIT_API_PRODUCTS_FAILED';
