export const ADD_API_FILTERS_REQUEST = 'ADD_API_FILTERS_REQUEST';
export const ADD_API_FILTERS_SUCCEEDED = 'ADD_API_FILTERS_SUCCEEDED';
export const ADD_API_FILTERS_FAILED = 'ADD_API_FILTERS_FAILED';

export const GET_API_FILTERS_REQUEST = 'GET_API_FILTERS_REQUEST';
export const GET_API_FILTERS_SUCCEEDED = 'GET_API_FILTERS_SUCCEEDED';
export const GET_API_FILTERS_FAILED = 'GET_API_FILTERS_FAILED';

export const GET_ID_API_FILTERS_REQUEST = 'GET_ID_API_FILTERS_REQUEST';
export const GET_ID_API_FILTERS_SUCCEEDED = 'GET_ID_API_FILTERS_SUCCEEDED';
export const GET_ID_API_FILTERS_FAILED = 'GET_ID_API_FILTERS_FAILED';

export const DELETE_API_FILTERS_REQUEST = 'DELETE_API_FILTERS_REQUEST';
export const DELETE_API_FILTERS_SUCCEEDED = 'DELETE_API_FILTERS_SUCCEEDED';
export const DELETE_API_FILTERS_FAILED = 'DELETE_API_FILTERS_FAILED';

export const EDIT_API_FILTERS_REQUEST = 'EDIT_API_FILTERS_REQUEST';
export const EDIT_API_FILTERS_SUCCEEDED = 'EDIT_API_FILTERS_SUCCEEDED';
export const EDIT_API_FILTERS_FAILED = 'EDIT_API_FILTERS_FAILED';
