export const REGISTRATION_API_REQUEST = 'REGISTRATION_API_REQUEST';
export const REGISTRATION_API_SUCCEEDED = 'REGISTRATION_API_SUCCEEDED';
export const REGISTRATION_API_FAILED = 'REGISTRATION_API_FAILED';

export const GET_DATA_THROUGH_JWT_CLIENT_REQUEST = 'GET_DATA_THROUGH_JWT_CLIENT_REQUEST';
export const GET_DATA_THROUGH_JWT_CLIENT_SUCCEEDED = 'GET_DATA_THROUGH_JWT_CLIENT_SUCCEEDED';
export const GET_DATA_THROUGH_JWT_CLIENT_SUCCEEDED_BUT_ENABLED =
  'GET_DATA_THROUGH_JWT_CLIENT_SUCCEEDED_BUT_ENABLED';
export const GET_DATA_THROUGH_JWT_CLIENT_FAILED = 'GET_DATA_THROUGH_JWT_CLIENT_FAILED';

export const DELETE_API_REQUEST = 'DELETE_API_REQUEST';
export const DELETE_API_SUCCEEDED = 'DELETE_API_SUCCEEDED';
export const DELETE_API_FAILED = 'DELETE_API_FAILED';

export const EDIT_API_PROFILE_REQUEST = 'EDIT_API_REQUEST';
export const EDIT_API_PROFILE_SUCCEEDED = 'EDIT_API_SUCCEEDED';
export const EDIT_API_PROFILE_FAILED = 'EDIT_API_FAILED';
