export const LOG_IN_API_REQUEST = 'LOG_IN_API_REQUEST';
export const LOG_IN_API_GET_TOKEN_SUCCEEDED = 'LOG_IN_API_GET_TOKEN_SUCCEEDED';
export const LOG_IN_API_SUCCEEDED = 'LOG_IN_API_SUCCEEDED';
export const LOG_IN_API_FAILED = 'LOG_IN_API_FAILED';

