export const LOG_IN_API_REQUEST = 'LOG_IN_API_REQUEST';
export const LOG_IN_API_GET_TOKEN_SUCCEEDED = 'LOG_IN_API_GET_TOKEN_SUCCEEDED';
export const LOG_IN_API_SUCCEEDED = 'LOG_IN_API_SUCCEEDED';
export const LOG_IN_API_FAILED = 'LOG_IN_API_FAILED';
export const LOG_OUT = 'LOG_OUT';
export const OPEN_WINDOW_AUTH = 'OPEN_WINDOW_AUTH';
export const CLOSE_WINDOW_AUTH = 'CLOSE_WINDOW_AUTH';
