export const GET_ITEMS = 'GET_ITEMS';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const ITEMS_ERROR = 'ITEMS_ERROR';
export const RESET_ITEM = 'RESET_ITEM';
export const REPLACE_WITH_ONLINE_CART = 'REPLACE_WITH_ONLINE_CART';
