export const CHANGE_NEXT_STEP = 'STATUS_NEXT_STEP';
export const CHANGE_STEP = 'CHANGE_STEP';
export const CHANGE_STEP_OF_LENGTH = 'CHANGE_STEP_OF_LENGTH';
export const SPECIFY_PERSONAL_DATA = 'SPECIFY_PERSONAL_DATA';
export const SPECIFY_DELIVERY_DATA = 'SPECIFY_DELIVERY_DATA';
export const SPECIFY_PAYMENT_DATA = 'SPECIFY_PAYMENT_DATA';
