export const CONFIGURATION_API_REQUEST = 'CONFIGURATION_API_REQUEST';
export const CONFIGURATION_API_SUCCEEDED = 'CONFIGURATION_API_SUCCEEDED';
export const CONFIGURATION_API_FAILED = 'CONFIGURATION_API_FAILED';
