export const ADD_API_REQUEST = 'ADD_API_REQUEST';
export const ADD_API_SUCCEEDED = 'ADD_API_SUCCEEDED';
export const ADD_API_FAILED = 'ADD_API_FAILED';

export const DELETE_API_REQUEST = 'DELETE_API_REQUEST';
export const DELETE_API_SUCCEEDED = 'DELETE_API_SUCCEEDED';
export const DELETE_API_FAILED = 'DELETE_API_FAILED';

export const SAVE_EMAIL = 'SAVE_EMAIL';
