export const GET_CUSTOMID_API_REQUEST = 'GET_CUSTOMID_API_REQUEST';
export const GET_CUSTOMID_API_SUCCEEDED = 'GET_CUSTOMID_API_SUCCEEDED';
export const GET_CUSTOMID_API_FAILED = 'GET_CUSTOMID_API_FAILED';
