export const GET_API_ROOT_CATEGORIES_REQUEST = 'GET_API_ROOT_CATEGORIES_REQUEST';
export const GET_API_ROOT_CATEGORIES_SUCCEEDED = 'GET_API_ROOT_CATEGORIES_SUCCEEDED';
export const GET_API_ROOT_CATEGORIES_FAILED = 'GET_API_ROOT_CATEGORIES_FAILED';

export const GET_API_CHILD_CATEGORIES_REQUEST = 'GET_API_CHILD_CATEGORIES_REQUEST';
export const GET_API_CHILD_CATEGORIES_SUCCEEDED = 'GET_API_CHILD_CATEGORIES_SUCCEEDED';
export const GET_API_CHILD_CATEGORIES_FAILED = 'GET_API_CHILD_CATEGORIES_FAILED';
