export const FIND_API_PRODUCTS_REQUEST = 'FIND_API_PRODUCTS_REQUEST';
export const FIND_API_PRODUCTS_SUCCEEDED = 'FIND_API_PRODUCTS_SUCCEEDED';
export const FIND_API_PRODUCTS_FAILED = 'FIND_API_PRODUCTS_FAILED';
