export const GET_API_PARTNERS_REQUEST = 'GET_API_PARTNERS_REQUEST';
export const GET_API_PARTNERS_SUCCEEDED = 'GET_API_PARTNERS_SUCCEEDED';
export const GET_API_PARTNERS_FAILED = 'GET_API_PARTNERS_FAILED';
