export const GET_PRODUCT = 'GET_PRODUCT';
export const REQUEST_PRODUCT = 'REQUEST_PRODUCT';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';

export const GET_COMMENT = 'GET_COMMENT';
export const COMMENT_ERROR = 'COMMENT_ERROR';
export const EDIT_SELECTED_IMG = 'EDIT_SELECTED_IMG';
